#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

all: debug release profile deploy deployprofile deploytosteam deploytestdebug deploytest deploytestsubmodules releasesubmodules linuxdeploy profilecustom profilecustomgcc

clean: clean_debug clean_release clean_profile clean_deploy clean_deployprofile clean_deploytosteam clean_deploytestdebug clean_deploytest clean_deploytestsubmodules clean_releasesubmodules clean_linuxdeploy clean_profilecustom clean_profilecustomgcc

.PHONY: 

