#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = -Ideps
CFLAGS = -Wall -fexceptions -Wno-narrowing -std=gnu++1z -DNET_CLIENT -DNO_COMPRESSION
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = -lmingw32 -lsfml-graphics -lsfml-audio -lsfml-network -lsfml-window -lsfml-system -lfreetype -lopengl32 -lws2_32 -lflac -lopenal32 -logg -lboost_system-mt -lmswsock -lole32

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g -DLOCAL_IP
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/crapmud_client

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2 -DLOCAL_IP
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release
DEP_RELEASE = 
OUT_RELEASE = bin/Release/crapmud_client

INC_PROFILE = $(INC)
CFLAGS_PROFILE = $(CFLAGS) -pg -Og -g -DLOCAL_IP
RESINC_PROFILE = $(RESINC)
RCFLAGS_PROFILE = $(RCFLAGS)
LIBDIR_PROFILE = $(LIBDIR)
LIB_PROFILE = $(LIB)
LDFLAGS_PROFILE = $(LDFLAGS) -pg -lgmon
OBJDIR_PROFILE = obj/Profile
DEP_PROFILE = 
OUT_PROFILE = bin/Profile/crapmud_client

INC_DEPLOY = $(INC)
CFLAGS_DEPLOY = $(CFLAGS) -O2 -DEXTERN_IP
RESINC_DEPLOY = $(RESINC)
RCFLAGS_DEPLOY = $(RCFLAGS)
LIBDIR_DEPLOY = $(LIBDIR)
LIB_DEPLOY = $(LIB)
LDFLAGS_DEPLOY = $(LDFLAGS) -s
OBJDIR_DEPLOY = obj/Deploy
DEP_DEPLOY = 
OUT_DEPLOY = bin/Deploy/crapmud_client

INC_DEPLOYPROFILE = $(INC)
CFLAGS_DEPLOYPROFILE = $(CFLAGS) -pg -Og -g -DEXTERN_IP
RESINC_DEPLOYPROFILE = $(RESINC)
RCFLAGS_DEPLOYPROFILE = $(RCFLAGS)
LIBDIR_DEPLOYPROFILE = $(LIBDIR)
LIB_DEPLOYPROFILE = $(LIB)
LDFLAGS_DEPLOYPROFILE = $(LDFLAGS) -pg -lgmon
OBJDIR_DEPLOYPROFILE = obj/DeployProfile
DEP_DEPLOYPROFILE = 
OUT_DEPLOYPROFILE = bin/DeployProfile/crapmud_client

INC_DEPLOYTOSTEAM = $(INC)
CFLAGS_DEPLOYTOSTEAM = $(CFLAGS) -O2 -DEXTERN_IP
RESINC_DEPLOYTOSTEAM = $(RESINC)
RCFLAGS_DEPLOYTOSTEAM = $(RCFLAGS)
LIBDIR_DEPLOYTOSTEAM = $(LIBDIR)
LIB_DEPLOYTOSTEAM = $(LIB)
LDFLAGS_DEPLOYTOSTEAM = $(LDFLAGS) -s
OBJDIR_DEPLOYTOSTEAM = obj/Deploy
DEP_DEPLOYTOSTEAM = 
OUT_DEPLOYTOSTEAM = bin/Deploy/crapmud_client

INC_LINUX = $(INC)
CFLAGS_LINUX = $(CFLAGS) -O2 -DEXTERN_IP
RESINC_LINUX = $(RESINC)
RCFLAGS_LINUX = $(RCFLAGS)
LIBDIR_LINUX = $(LIBDIR)
LIB_LINUX = $(LIB)
LDFLAGS_LINUX = $(LDFLAGS) -s
OBJDIR_LINUX = obj/Deploy
DEP_LINUX = 
OUT_LINUX = bin/Deploy/crapmud_client

OBJ_DEBUG = $(OBJDIR_DEBUG)/auto_handlers.o $(OBJDIR_DEBUG)/deps/serialise/serialise.o $(OBJDIR_DEBUG)/http_beast_client.o $(OBJDIR_DEBUG)/main.o $(OBJDIR_DEBUG)/string_helpers.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/auto_handlers.o $(OBJDIR_RELEASE)/deps/serialise/serialise.o $(OBJDIR_RELEASE)/http_beast_client.o $(OBJDIR_RELEASE)/main.o $(OBJDIR_RELEASE)/string_helpers.o

OBJ_PROFILE = $(OBJDIR_PROFILE)/auto_handlers.o $(OBJDIR_PROFILE)/deps/serialise/serialise.o $(OBJDIR_PROFILE)/http_beast_client.o $(OBJDIR_PROFILE)/main.o $(OBJDIR_PROFILE)/string_helpers.o

OBJ_DEPLOY = $(OBJDIR_DEPLOY)/auto_handlers.o $(OBJDIR_DEPLOY)/deps/serialise/serialise.o $(OBJDIR_DEPLOY)/http_beast_client.o $(OBJDIR_DEPLOY)/icon.o $(OBJDIR_DEPLOY)/main.o $(OBJDIR_DEPLOY)/string_helpers.o

OBJ_DEPLOYPROFILE = $(OBJDIR_DEPLOYPROFILE)/auto_handlers.o $(OBJDIR_DEPLOYPROFILE)/deps/serialise/serialise.o $(OBJDIR_DEPLOYPROFILE)/http_beast_client.o $(OBJDIR_DEPLOYPROFILE)/main.o $(OBJDIR_DEPLOYPROFILE)/string_helpers.o

OBJ_DEPLOYTOSTEAM = $(OBJDIR_DEPLOYTOSTEAM)/auto_handlers.o $(OBJDIR_DEPLOYTOSTEAM)/deps/serialise/serialise.o $(OBJDIR_DEPLOYTOSTEAM)/http_beast_client.o $(OBJDIR_DEPLOYTOSTEAM)/main.o $(OBJDIR_DEPLOYTOSTEAM)/string_helpers.o

OBJ_LINUX = $(OBJDIR_LINUX)/auto_handlers.o $(OBJDIR_LINUX)/deps/serialise/serialise.o $(OBJDIR_LINUX)/http_beast_client.o $(OBJDIR_LINUX)/icon.o $(OBJDIR_LINUX)/main.o $(OBJDIR_LINUX)/string_helpers.o

all: debug release profile deploy deployprofile deploytosteam linux

clean: clean_debug clean_release clean_profile clean_deploy clean_deployprofile clean_deploytosteam clean_linux

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)
	test -d $(OBJDIR_DEBUG)/deps/serialise || mkdir -p $(OBJDIR_DEBUG)/deps/serialise

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/auto_handlers.o: auto_handlers.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c auto_handlers.cpp -o $(OBJDIR_DEBUG)/auto_handlers.o

$(OBJDIR_DEBUG)/deps/serialise/serialise.o: deps/serialise/serialise.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c deps/serialise/serialise.cpp -o $(OBJDIR_DEBUG)/deps/serialise/serialise.o

$(OBJDIR_DEBUG)/http_beast_client.o: http_beast_client.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c http_beast_client.cpp -o $(OBJDIR_DEBUG)/http_beast_client.o

$(OBJDIR_DEBUG)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.cpp -o $(OBJDIR_DEBUG)/main.o

$(OBJDIR_DEBUG)/string_helpers.o: string_helpers.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c string_helpers.cpp -o $(OBJDIR_DEBUG)/string_helpers.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)
	rm -rf $(OBJDIR_DEBUG)/deps/serialise

before_release: 
	test -d bin/Release || mkdir -p bin/Release
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)
	test -d $(OBJDIR_RELEASE)/deps/serialise || mkdir -p $(OBJDIR_RELEASE)/deps/serialise

after_release: 
	build_test.bat

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/auto_handlers.o: auto_handlers.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c auto_handlers.cpp -o $(OBJDIR_RELEASE)/auto_handlers.o

$(OBJDIR_RELEASE)/deps/serialise/serialise.o: deps/serialise/serialise.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c deps/serialise/serialise.cpp -o $(OBJDIR_RELEASE)/deps/serialise/serialise.o

$(OBJDIR_RELEASE)/http_beast_client.o: http_beast_client.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c http_beast_client.cpp -o $(OBJDIR_RELEASE)/http_beast_client.o

$(OBJDIR_RELEASE)/main.o: main.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.cpp -o $(OBJDIR_RELEASE)/main.o

$(OBJDIR_RELEASE)/string_helpers.o: string_helpers.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c string_helpers.cpp -o $(OBJDIR_RELEASE)/string_helpers.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release
	rm -rf $(OBJDIR_RELEASE)
	rm -rf $(OBJDIR_RELEASE)/deps/serialise

before_profile: 
	test -d bin/Profile || mkdir -p bin/Profile
	test -d $(OBJDIR_PROFILE) || mkdir -p $(OBJDIR_PROFILE)
	test -d $(OBJDIR_PROFILE)/deps/serialise || mkdir -p $(OBJDIR_PROFILE)/deps/serialise

after_profile: 

profile: before_profile out_profile after_profile

out_profile: before_profile $(OBJ_PROFILE) $(DEP_PROFILE)
	$(LD) $(LIBDIR_PROFILE) -o $(OUT_PROFILE) $(OBJ_PROFILE)  $(LDFLAGS_PROFILE) $(LIB_PROFILE)

$(OBJDIR_PROFILE)/auto_handlers.o: auto_handlers.cpp
	$(CXX) $(CFLAGS_PROFILE) $(INC_PROFILE) -c auto_handlers.cpp -o $(OBJDIR_PROFILE)/auto_handlers.o

$(OBJDIR_PROFILE)/deps/serialise/serialise.o: deps/serialise/serialise.cpp
	$(CXX) $(CFLAGS_PROFILE) $(INC_PROFILE) -c deps/serialise/serialise.cpp -o $(OBJDIR_PROFILE)/deps/serialise/serialise.o

$(OBJDIR_PROFILE)/http_beast_client.o: http_beast_client.cpp
	$(CXX) $(CFLAGS_PROFILE) $(INC_PROFILE) -c http_beast_client.cpp -o $(OBJDIR_PROFILE)/http_beast_client.o

$(OBJDIR_PROFILE)/main.o: main.cpp
	$(CXX) $(CFLAGS_PROFILE) $(INC_PROFILE) -c main.cpp -o $(OBJDIR_PROFILE)/main.o

$(OBJDIR_PROFILE)/string_helpers.o: string_helpers.cpp
	$(CXX) $(CFLAGS_PROFILE) $(INC_PROFILE) -c string_helpers.cpp -o $(OBJDIR_PROFILE)/string_helpers.o

clean_profile: 
	rm -f $(OBJ_PROFILE) $(OUT_PROFILE)
	rm -rf bin/Profile
	rm -rf $(OBJDIR_PROFILE)
	rm -rf $(OBJDIR_PROFILE)/deps/serialise

before_deploy: 
	test -d bin/Deploy || mkdir -p bin/Deploy
	test -d $(OBJDIR_DEPLOY) || mkdir -p $(OBJDIR_DEPLOY)
	test -d $(OBJDIR_DEPLOY)/deps/serialise || mkdir -p $(OBJDIR_DEPLOY)/deps/serialise

after_deploy: 
	build_release.bat

deploy: before_deploy out_deploy after_deploy

out_deploy: before_deploy $(OBJ_DEPLOY) $(DEP_DEPLOY)
	$(LD) $(LIBDIR_DEPLOY) -o $(OUT_DEPLOY) $(OBJ_DEPLOY)  $(LDFLAGS_DEPLOY) $(LIB_DEPLOY)

$(OBJDIR_DEPLOY)/auto_handlers.o: auto_handlers.cpp
	$(CXX) $(CFLAGS_DEPLOY) $(INC_DEPLOY) -c auto_handlers.cpp -o $(OBJDIR_DEPLOY)/auto_handlers.o

$(OBJDIR_DEPLOY)/deps/serialise/serialise.o: deps/serialise/serialise.cpp
	$(CXX) $(CFLAGS_DEPLOY) $(INC_DEPLOY) -c deps/serialise/serialise.cpp -o $(OBJDIR_DEPLOY)/deps/serialise/serialise.o

$(OBJDIR_DEPLOY)/http_beast_client.o: http_beast_client.cpp
	$(CXX) $(CFLAGS_DEPLOY) $(INC_DEPLOY) -c http_beast_client.cpp -o $(OBJDIR_DEPLOY)/http_beast_client.o

$(OBJDIR_DEPLOY)/icon.o: icon.res
	$(WINDRES) -i icon.res -J rc -o $(OBJDIR_DEPLOY)/icon.o -O coff $(INC_DEPLOY)

$(OBJDIR_DEPLOY)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEPLOY) $(INC_DEPLOY) -c main.cpp -o $(OBJDIR_DEPLOY)/main.o

$(OBJDIR_DEPLOY)/string_helpers.o: string_helpers.cpp
	$(CXX) $(CFLAGS_DEPLOY) $(INC_DEPLOY) -c string_helpers.cpp -o $(OBJDIR_DEPLOY)/string_helpers.o

clean_deploy: 
	rm -f $(OBJ_DEPLOY) $(OUT_DEPLOY)
	rm -rf bin/Deploy
	rm -rf $(OBJDIR_DEPLOY)
	rm -rf $(OBJDIR_DEPLOY)/deps/serialise

before_deployprofile: 
	test -d bin/DeployProfile || mkdir -p bin/DeployProfile
	test -d $(OBJDIR_DEPLOYPROFILE) || mkdir -p $(OBJDIR_DEPLOYPROFILE)
	test -d $(OBJDIR_DEPLOYPROFILE)/deps/serialise || mkdir -p $(OBJDIR_DEPLOYPROFILE)/deps/serialise

after_deployprofile: 

deployprofile: before_deployprofile out_deployprofile after_deployprofile

out_deployprofile: before_deployprofile $(OBJ_DEPLOYPROFILE) $(DEP_DEPLOYPROFILE)
	$(LD) $(LIBDIR_DEPLOYPROFILE) -o $(OUT_DEPLOYPROFILE) $(OBJ_DEPLOYPROFILE)  $(LDFLAGS_DEPLOYPROFILE) $(LIB_DEPLOYPROFILE)

$(OBJDIR_DEPLOYPROFILE)/auto_handlers.o: auto_handlers.cpp
	$(CXX) $(CFLAGS_DEPLOYPROFILE) $(INC_DEPLOYPROFILE) -c auto_handlers.cpp -o $(OBJDIR_DEPLOYPROFILE)/auto_handlers.o

$(OBJDIR_DEPLOYPROFILE)/deps/serialise/serialise.o: deps/serialise/serialise.cpp
	$(CXX) $(CFLAGS_DEPLOYPROFILE) $(INC_DEPLOYPROFILE) -c deps/serialise/serialise.cpp -o $(OBJDIR_DEPLOYPROFILE)/deps/serialise/serialise.o

$(OBJDIR_DEPLOYPROFILE)/http_beast_client.o: http_beast_client.cpp
	$(CXX) $(CFLAGS_DEPLOYPROFILE) $(INC_DEPLOYPROFILE) -c http_beast_client.cpp -o $(OBJDIR_DEPLOYPROFILE)/http_beast_client.o

$(OBJDIR_DEPLOYPROFILE)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEPLOYPROFILE) $(INC_DEPLOYPROFILE) -c main.cpp -o $(OBJDIR_DEPLOYPROFILE)/main.o

$(OBJDIR_DEPLOYPROFILE)/string_helpers.o: string_helpers.cpp
	$(CXX) $(CFLAGS_DEPLOYPROFILE) $(INC_DEPLOYPROFILE) -c string_helpers.cpp -o $(OBJDIR_DEPLOYPROFILE)/string_helpers.o

clean_deployprofile: 
	rm -f $(OBJ_DEPLOYPROFILE) $(OUT_DEPLOYPROFILE)
	rm -rf bin/DeployProfile
	rm -rf $(OBJDIR_DEPLOYPROFILE)
	rm -rf $(OBJDIR_DEPLOYPROFILE)/deps/serialise

before_deploytosteam: 
	test -d bin/Deploy || mkdir -p bin/Deploy
	test -d $(OBJDIR_DEPLOYTOSTEAM) || mkdir -p $(OBJDIR_DEPLOYTOSTEAM)
	test -d $(OBJDIR_DEPLOYTOSTEAM)/deps/serialise || mkdir -p $(OBJDIR_DEPLOYTOSTEAM)/deps/serialise

after_deploytosteam: 
	build_release.bat
	C:/Users/James/Downloads/steamworks_sdk_142/sdk/tools/ContentBuilder/run_build.bat

deploytosteam: before_deploytosteam out_deploytosteam after_deploytosteam

out_deploytosteam: before_deploytosteam $(OBJ_DEPLOYTOSTEAM) $(DEP_DEPLOYTOSTEAM)
	$(LD) $(LIBDIR_DEPLOYTOSTEAM) -o $(OUT_DEPLOYTOSTEAM) $(OBJ_DEPLOYTOSTEAM)  $(LDFLAGS_DEPLOYTOSTEAM) $(LIB_DEPLOYTOSTEAM)

$(OBJDIR_DEPLOYTOSTEAM)/auto_handlers.o: auto_handlers.cpp
	$(CXX) $(CFLAGS_DEPLOYTOSTEAM) $(INC_DEPLOYTOSTEAM) -c auto_handlers.cpp -o $(OBJDIR_DEPLOYTOSTEAM)/auto_handlers.o

$(OBJDIR_DEPLOYTOSTEAM)/deps/serialise/serialise.o: deps/serialise/serialise.cpp
	$(CXX) $(CFLAGS_DEPLOYTOSTEAM) $(INC_DEPLOYTOSTEAM) -c deps/serialise/serialise.cpp -o $(OBJDIR_DEPLOYTOSTEAM)/deps/serialise/serialise.o

$(OBJDIR_DEPLOYTOSTEAM)/http_beast_client.o: http_beast_client.cpp
	$(CXX) $(CFLAGS_DEPLOYTOSTEAM) $(INC_DEPLOYTOSTEAM) -c http_beast_client.cpp -o $(OBJDIR_DEPLOYTOSTEAM)/http_beast_client.o

$(OBJDIR_DEPLOYTOSTEAM)/main.o: main.cpp
	$(CXX) $(CFLAGS_DEPLOYTOSTEAM) $(INC_DEPLOYTOSTEAM) -c main.cpp -o $(OBJDIR_DEPLOYTOSTEAM)/main.o

$(OBJDIR_DEPLOYTOSTEAM)/string_helpers.o: string_helpers.cpp
	$(CXX) $(CFLAGS_DEPLOYTOSTEAM) $(INC_DEPLOYTOSTEAM) -c string_helpers.cpp -o $(OBJDIR_DEPLOYTOSTEAM)/string_helpers.o

clean_deploytosteam: 
	rm -f $(OBJ_DEPLOYTOSTEAM) $(OUT_DEPLOYTOSTEAM)
	rm -rf bin/Deploy
	rm -rf $(OBJDIR_DEPLOYTOSTEAM)
	rm -rf $(OBJDIR_DEPLOYTOSTEAM)/deps/serialise

before_linux: 
	test -d bin/Deploy || mkdir -p bin/Deploy
	test -d $(OBJDIR_LINUX) || mkdir -p $(OBJDIR_LINUX)
	test -d $(OBJDIR_LINUX)/deps/serialise || mkdir -p $(OBJDIR_LINUX)/deps/serialise

after_linux: 

linux: before_linux out_linux after_linux

out_linux: before_linux $(OBJ_LINUX) $(DEP_LINUX)
	$(LD) $(LIBDIR_LINUX) -o $(OUT_LINUX) $(OBJ_LINUX)  $(LDFLAGS_LINUX) $(LIB_LINUX)

$(OBJDIR_LINUX)/auto_handlers.o: auto_handlers.cpp
	$(CXX) $(CFLAGS_LINUX) $(INC_LINUX) -c auto_handlers.cpp -o $(OBJDIR_LINUX)/auto_handlers.o

$(OBJDIR_LINUX)/deps/serialise/serialise.o: deps/serialise/serialise.cpp
	$(CXX) $(CFLAGS_LINUX) $(INC_LINUX) -c deps/serialise/serialise.cpp -o $(OBJDIR_LINUX)/deps/serialise/serialise.o

$(OBJDIR_LINUX)/http_beast_client.o: http_beast_client.cpp
	$(CXX) $(CFLAGS_LINUX) $(INC_LINUX) -c http_beast_client.cpp -o $(OBJDIR_LINUX)/http_beast_client.o

$(OBJDIR_LINUX)/icon.o: icon.res
	$(WINDRES) -i icon.res -J rc -o $(OBJDIR_LINUX)/icon.o -O coff $(INC_LINUX)

$(OBJDIR_LINUX)/main.o: main.cpp
	$(CXX) $(CFLAGS_LINUX) $(INC_LINUX) -c main.cpp -o $(OBJDIR_LINUX)/main.o

$(OBJDIR_LINUX)/string_helpers.o: string_helpers.cpp
	$(CXX) $(CFLAGS_LINUX) $(INC_LINUX) -c string_helpers.cpp -o $(OBJDIR_LINUX)/string_helpers.o

clean_linux: 
	rm -f $(OBJ_LINUX) $(OUT_LINUX)
	rm -rf bin/Deploy
	rm -rf $(OBJDIR_LINUX)
	rm -rf $(OBJDIR_LINUX)/deps/serialise

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release before_profile after_profile clean_profile before_deploy after_deploy clean_deploy before_deployprofile after_deployprofile clean_deployprofile before_deploytosteam after_deploytosteam clean_deploytosteam before_linux after_linux clean_linux

